# if using crez-sw-ingest script, add   -s prod   or whatever to command line
# otherwise, add SETTINGS='prod'  or whatever to command like of rake task

# settings for production
prod:
  solrmarc_dist_dir: /home/blacklight/solrmarc-sw/dist
  solrmarc_conf_props_file: sw_config.properties
  solr_url: http://127.0.0.1:8983/solr
  solrj_jar_dir: /home/blacklight/solrmarc-sw/dist/lib
  solrj_num_threads: 4
  log_level: error

# settings for tests (default)
test:
  solrmarc_dist_dir: solrmarc-sw/dist
  solrmarc_conf_props_file: sw_config.properties
  solr_url: http://localhost:8983/solr/
  solr_source_url: http://sul-solr.stanford.edu/solr/searchworks-prod
  solrj_jar_dir: solrmarc-sw/dist/lib
  solrj_num_threads: 1
  log_level: info
    
# add:
#solr id field?
#solr marcxml field?
