# if using crez-sw-ingest script, add   -s test   or whatever to command line
# otherwise, add SETTINGS='ci'  or whatever to command like of rake task

# settings for production
prod:
  solrmarc_dist_dir: /home/blacklight/solrmarc-sw/dist
  solrmarc_conf_props_file: sw_config.properties
  solr_url: http://127.0.0.1:8983/solr
  lucene_req_handler: standard
  solrj_jar_dir: /home/blacklight/solrmarc-sw/dist/lib
  solrj_queue_size: 20
  solrj_num_threads: 4
  log_level: error

# settings for running local tests
test:
  solrmarc_dist_dir: solrmarc-sw/dist
  solrmarc_conf_props_file: sw_config.properties
  solr_url: http://localhost:8983/solr/
  solr_source_url: http://sw-solr-test-b.stanford.edu:8983/solr/
  lucene_req_handler: standard
  solrj_queue_size: 20
  solrj_num_threads: 1
  log_level: info

# settings for continuous integration
ci:
  solrmarc_dist_dir: /hudson/home/hudson/hudson/jobs/solrmarc-SW-dist/workspace/dist
  solrmarc_conf_props_file: sw_config.properties
# FIXME:  this should be a local jetty with solr spun up from within the app for testing  
  solr_url: http://localhost:8983/solr
  solr_source_url: http://sw-solr-g.stanford.edu:8983/solr
  
  lucene_req_handler: standard
  solrj_jar_dir: /hudson/home/hudson/hudson/jobs/solrmarc-SW-dist/workspace/dist/lib
  solrj_queue_size: 20
  solrj_num_threads: 1
  log_level: info
    
# add:
#solr id field?
#solr marcxml field?
